### ISSUE TITLE
Issue when running the first artisan db:seed command from the installation.

### ISSUE THREAD

**Issue by rhanmiano** [woenel/prpcmblmts#4]
Hi, I'm trying your package out but stumbled upon an error when issuing `db:seed` command. Followed all the commands mentioned in the installation section of readme.

Please see image for reference.

![image](https://user-images.githubusercontent.com/31644925/183930051-7d320c9a-27a0-4a9e-a43c-f2dcef945602.png)

PHP 7.4.23 
Composer version 2.1
Laravel 8.54

**Comment by woenel** [comment]
Hi, have you executed the `composer dump-autoload` before the `db:seed`?

**Comment by rhanmiano** [comment]
Hi @woenel , yes I did. What I did for the meantime is manually imported the sql files into my local database.

**Comment by romilj** [comment]
Hi @woenel, I created a PR to fix this one. :)

**Comment by nare-nasi** [comment]
Hi, have you fix the issue.

**Comment by woenel** [comment]
@nare-nasi fix released. See PR: https://github.com/woenel/prpcmblmts/pull/6
